### ISSUE TITLE
Interval algo

### ISSUE THREAD

**Issue by timkurvers** [hyperoslo/rope-pull#1]
Had a quick look at the interval algorithm and wondering: how many taps can a player perform within 100ms? I'm assuming it's about 1 to 2 taps?

Wouldn't the current implementation feel rather unresponsive, as your taps never actually influence the rope directly?

**Comment by jgorset** [comment]
Probably just one. It doesn't really feel unresponsive, though, at least not to me. If you can make one that feels even more responsive I'm all for it, but keep in mind that it has to scale across at least 40 people clicking manically.

**Comment by timkurvers** [comment]
:scream:

**Comment by 3lvis** [comment]
I've been discussing this a bit with @timkurvers.

I guess the idea is that you want two things:
- Feedback of your taps.
- Get the sense of losing (so you can get a bit excited and scream to your team HAARRRDEEERRRR).

One way you could achieve this is by making the turns a bit larger, for example I will tap 10 times and those times I will see my side building up a bit, then suddenly I will see a big pull from the other team (which will be a build up during x amount of taps from the other team) then me and my team will tap harder and start building up our taps so we can counter attack the other teams pull.

**Comment by jgorset** [comment]
Cool idea!
